name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Create appsettings.json
      run: |
        echo '{
          "GoogleSheets": {
            "ApiKey": "${{ secrets.GOOGLE_SHEETS_API_KEY }}",
            "MasterSpreadsheetId": "${{ secrets.MASTER_SPREADSHEET_ID }}"
          }
        }' > MickeyInfoUtility/MickeyInfoUtility/wwwroot/appsettings.json
    
    - name: Publish .NET Core Project
      run: dotnet publish MickeyInfoUtility/MickeyInfoUtility/MickeyInfoUtility.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/MickeyInfoUtility\/" \/>/g' release/wwwroot/index.html
    
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: release/wwwroot
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2